# Generated by Django 4.2.16 on 2025-04-07 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Назва фільму')),
                ('duration', models.DurationField(verbose_name='Тривалість')),
            ],
            options={
                'verbose_name': 'Фільм',
                'verbose_name_plural': 'Фільми',
            },
        ),
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва залу')),
                ('capacity', models.PositiveIntegerField(verbose_name='Місткість')),
            ],
            options={
                'verbose_name': 'Зал',
                'verbose_name_plural': 'Зали',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Час початку')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.film', verbose_name='Фільм')),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.hall', verbose_name='Зал')),
            ],
            options={
                'verbose_name': 'Розклад',
                'verbose_name_plural': 'Розклад',
            },
        ),
    ]
